apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  # Uncomment for using a custom certificate
  #- name: awx-secret-tls
  #  type: kubernetes.io/tls
  #  files:
  #    - tls.crt
  #    - tls.key
  
  # Uncomment for bypassing Postgres configuration
  #- name: awx-postgres-configuration
  #  type: Opaque
  #  literals:
  #    - host=awx-postgres-13
  #    - port=5432
  #    - database=awx
  #    - username=awx
  #    - password=Ansible123!
  #    - type=managed
  #    - sslmode=prefer

  - name: awx-admin-password
    type: Opaque
    # Select custom password for Admin
    literals:
      - password=SomePass123@

resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=1.1.3
  - pv.yml
  - pvc.yml
  - awx.yml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 1.1.3

# Specify a custom namespace in which to install AWX
namespace: awx