#---
# Uncomment if there is a need for a persistent postgres volume
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: awx-postgres-13-volume
#spec:
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  capacity:
#    storage: 8Gi
#  storageClassName: awx-postgres-volume
#  hostPath:
#    path: /awx-data/postgres-13

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: awx-projects-volume
  hostPath:
    # Modify to the path you have created projects folder at
    path: /home/ec2-user/awx-data/projects