---
# Load policy into root branch
# This policy defines a demo organization for testing basic capabilities

# Define Admins, create admins group, create admin01 user
- !group
  id: admins 
  owner: !user admin

- !user
  id: admin01
  owner: !group admins

- !permit
  role: !group admins
  privileges: [read,update,create]
  resource: !policy root

- !grant
  role: !group admins
  members: 
    - !user admin01

# Define ansible branch, create users, hosts, groups, layers, variables
- !policy
  id: ansible
  owner: !group admins

# ansible/managers group will admin everything under ansible branch
- !group
  id: ansible/managers
  owner: !group admins

- !permit
  role: !group ansible/managers
  privileges: [read,update,create]
  resource: !policy ansible

- !permit
  role: !group ansible/managers
  privileges: [read,update,create]
  resource: !group ansible/managers

- !user
  id: ansible-manager01
  owner: !group ansible/managers

- !grant
  role: !group ansible/managers
  members: 
    - !user ansible-manager01
