# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  consume-secrets-from-conjur:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Authenticating to Conjur"
          command: |
            # Store Conjur Token in temp file
            TOKEN=$(curl -s -k --request POST "$CONJUR_FQDN/authn-jwt/$AUTHN_ID/$CONJUR_ORG/authenticate" --header 'Content-Type: application/x-www-form-urlencoded' --header "Accept-Encoding: base64" --data-urlencode "jwt=$CIRCLE_OIDC_TOKEN")
            echo "export TOKEN=$TOKEN" >> "$BASH_ENV"
      - run:
          name: "Consuming secret from Conjur"
          command: |
            SECRET=$(curl -s -k -X GET -H "Authorization: Token token=\"$token\"" "$CONJUR_FQDN/secrets/$CONJUR_ORG/variable/circleci/apps/safe/secret1")
            echo "export SECRET=$SECRET" >> "$BASH_ENV"
      - run:
          name: "Print secret"
          command: |
            echo "================"
            echo "secret1: $SECRET"
            echo "================"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  get-secrets-workflow:
    jobs:
      - consume-secrets-from-conjur:
          context: Conjur
