---
fields:
  - id: variable_1
    type: string
    label: Variable 1 Path
    secret: true
  - id: variable_2
    type: string
    label: Variable 2 Path
    secret: true
  - id: variable_3
    type: string
    label: Variable 3 Path
    secret: true
required:
  - variable_1
  - variable_2
  - variable_3